title: "Paneltime"
description: "Integrating paneldata and and efficient ARIMA/GARCH estimation. "
baseurl: "https://github.com/paneltime/paneltime" # Leave empty if using a custom domain
url: "https://paneltime.github.io/paneltime/" # Change this to your GitHub Pages URL



# Markdown processor
markdown: kramdown
kramdown:
  toc_levels: 2..3 # TOC will include H2 and H3 headings



# Plugins (GitHub Pages-compatible ones)
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

